
"""
    evolution_operator(h::AbstractMatrix, Δt::Number)

Construct the two-site time-evolution operator generated by the local
Hamiltonian term `h` over a time step `Δt`,

    G(Δt) = exp(-im * Δt * h).

The matrix `h` is assumed to represent a nearest-neighbor Hamiltonian
term `hᵢ,ᵢ₊₁`. For a local physical dimension `d`, it therefore acts on
a two-site Hilbert space of dimension `d²` and has dimensions
`d² × d²`.

The argument `Δt` may be complex. In particular, imaginary-time
evolution can be obtained by passing

    Δt = -im * Δτ,

which gives

    G = exp(-Δτ * h).

# Arguments
- `h::AbstractMatrix`: Matrix representation of a two-site Hamiltonian
  term.
- `Δt::Number`: Real- or imaginary-time step.

# Returns
- `AbstractMatrix`: The two-site evolution operator
  `exp(-im * Δt * h)`.

# Throws
- `DimensionMismatch`: If `h` is not square.
"""
function evolution_operator(h::AbstractMatrix, Δt::Number)
    size(h, 1) == size(h, 2) ||
        throw(DimensionMismatch(
            "The two-site Hamiltonian must be a square matrix."
        ))

    return exp(-im * Δt * h)
end


"""
    split_two_site_operator(G::AbstractMatrix) -> L, R

Split a two-site operator `G` into two neighboring MPO tensors using a
singular value decomposition.

For two sites with equal local physical dimension `d`, `G` is a
`d² × d²` matrix with matrix elements

    G[(t₁, t₂), (b₁, b₂)],

where `t₁, t₂` are output physical indices and `b₁, b₂` are input
physical indices.

To obtain an MPO decomposition, the indices are regrouped by physical
site,

    (t₁, b₁) | (t₂, b₂),

and the resulting `d² × d²` matrix is decomposed as

    G_mat = U * S * V†.

This is an operator Schmidt decomposition across the bond between the
two sites. The SVD index becomes the MPO virtual bond index `μ`.

The singular values are absorbed symmetrically into the two factors,

    L_mat = U * sqrt(S),
    R_mat = sqrt(S) * V†,

so that

    G = Σ_μ L_μ ⊗ R_μ.

The returned tensors follow the MPO index convention

    O⁽ⁿ⁾[μₙ₋₁, tₙ, bₙ, μₙ].

Consequently, `L` and `R` have dimensions

    size(L) = (1, d, d, χ),
    size(R) = (χ, d, d, 1),

where `χ` is the operator Schmidt rank returned by the SVD.

# Index ordering

For a two-site operator constructed using Julia's `kron` convention,
reshaping

    reshape(G, d, d, d, d)

produces indices ordered as

    (t₂, t₁, b₂, b₁).

They are therefore permuted to

    (t₁, b₁, t₂, b₂)

before the SVD so that the decomposition separates the two physical
sites rather than separating input from output indices.

# Arguments
- `G::AbstractMatrix`: Two-site operator with dimensions `d² × d²`.

# Returns
- `L::Tensor`: Left MPO tensor with dimensions `(1, d, d, χ)`.
- `R::Tensor`: Right MPO tensor with dimensions `(χ, d, d, 1)`.

Contracting the right virtual bond of `L` with the left virtual bond of
`R` reconstructs the original two-site operator.

# Throws
- `DimensionMismatch`: If `G` is not square.
- `DimensionMismatch`: If the dimension of `G` is not the square of an
  integer local physical dimension.
"""
function split_two_site_operator(G::AbstractMatrix)
    size(G, 1) == size(G, 2) ||
        throw(DimensionMismatch(
            "The two-site operator must be a square matrix."
        ))
    
    # For two sites of equal local dimension d, G has size d² × d².
    d² = size(G, 1)
    d = isqrt(d²)

    d * d == d² ||
        throw(DimensionMismatch(
            "The matrix dimension must be the square of the local physical dimension."
        ))

    # We first expose the four physical indices of the d² × d² two-site
    # operator by reshaping it into a rank-4 tensor of size d × d × d × d.
    #
    # Assuming G uses the basis ordering produced by Julia's kron convention,
    # its matrix elements are
    #
    #     G_{(t₁, t₂), (b₁, b₂)},
    #
    # where (t₁, t₂) is the composite output index and (b₁, b₂) is the
    # composite input index.
    #
    # Julia stores arrays in column-major order, so reshape exposes the
    # faster-varying indices first. Since t₂ varies faster than t₁, and b₂
    # varies faster than b₁, the reshaped tensor has index order
    #
    #     (t₂, t₁, b₂, b₁).
    G_tensor = reshape(G, d, d, d, d)

    # For the MPO decomposition, we want to group the input and output
    # indices belonging to the same physical site:
    #
    #     site 1: (t₁, b₁)
    #     site 2: (t₂, b₂)
    #
    # Therefore we permute the tensor to
    #
    #     (t₁, b₁, t₂, b₂).
    G_perm = permutedims(G_tensor, (2, 4, 1, 3))

    # Fuse the output/input pair of each site into one composite index,
    # obtaining the matrix used for the operator Schmidt decomposition:
    #
    #     (t₁, b₁) | (t₂, b₂).
    G_mat = reshape(G_perm, d * d, d * d)

    # Operator Schmidt decomposition.
    F = svd(G_mat)

    χ = length(F.S)

    # Absorb half of the singular values into each side.
    sqrtS = sqrt.(F.S)

    L_mat = F.U * Diagonal(sqrtS)
    R_mat = Diagonal(sqrtS) * F.Vt

    # MPO convention:
    #
    #     O⁽ⁿ⁾[μₙ₋₁, tₙ, bₙ, μₙ]
    #
    # The outer virtual bonds are trivial.
    L = Tensor(reshape(L_mat, 1, d, d, χ))
    R = Tensor(reshape(R_mat, χ, d, d, 1))

    #            tᵢ             tᵢ₊₁
    #            |                |
    #        ┌───────┐ μ      ┌───────┐
    #    1 ──┤   L   ├────────┤   R   ├── 1
    #        └───────┘        └───────┘
    #            |                |
    #            bᵢ             bᵢ₊₁

    return L, R
end


"""
    identity_mpo_tensor(d::Int, ::Type{T}) -> Tensor{T,4}

Construct a single-site identity operator as an MPO tensor.

The returned tensor follows the MPO convention

    O[μ_left, t, b, μ_right]

and has dimensions

    (1, d, d, 1).

Both virtual bonds are trivial, while the physical indices contain the
`d × d` identity matrix,

    O[1, t, b, 1] = δ(t, b).

Such tensors are used to fill sites on which a particular Trotter layer
does not contain a two-site gate.

# Arguments
- `d::Int`: Local physical dimension.
- `T`: Element type of the identity tensor.

# Returns
- `Tensor{T,4}`: Rank-4 identity MPO tensor of size `(1, d, d, 1)`.
"""
function identity_mpo_tensor(d::Int, ::Type{T}) where {T}
    I_d = Matrix{T}(I, d, d)
    # Both virtual bonds have dimension 1.
    return Tensor(reshape(I_d, 1, d, d, 1))
end


"""
    trotter_mpos(h_terms, Δt) -> U_odd, U_even

Construct the odd and even MPO layers used in a first-order
Suzuki-Trotter decomposition of a nearest-neighbor Hamiltonian.

The Hamiltonian is assumed to have the form

    H = Σᵢ hᵢ,ᵢ₊₁,

with the convention

    h_terms[i] = hᵢ,ᵢ₊₁.

For `N` physical sites, `h_terms` therefore contains `N - 1`
two-site Hamiltonian matrices.

The Hamiltonian is divided into

    H_odd  = h₁,₂ + h₃,₄ + h₅,₆ + ...,
    H_even = h₂,₃ + h₄,₅ + h₆,₇ + ....

Within each group the two-site terms act on disjoint pairs of sites and
therefore commute. Their time-evolution operators can consequently be
written exactly as products of independent two-site gates,

    U_odd(Δt)
        = ∏_{i odd} exp(-im * Δt * hᵢ,ᵢ₊₁),

    U_even(Δt)
        = ∏_{i even} exp(-im * Δt * hᵢ,ᵢ₊₁).

Each two-site gate is split into two MPO tensors using
`split_two_site_operator`. Sites that are not acted on by a gate in a
given layer are filled with identity MPO tensors.

For example, for six sites the two MPO layers have the structure

    U_odd  = [L₁₂, R₁₂, L₃₄, R₃₄, L₅₆, R₅₆],

    U_even = [ I,  L₂₃, R₂₃, L₄₅, R₄₅,  I ].

These MPOs may then be used in the first-order Trotter approximation

    exp(-im * Δt * H)
        ≈ U_odd(Δt) * U_even(Δt).

The construction of each individual odd or even layer is exact; the
approximation arises from separating the evolution generated by
`H_odd + H_even` into the product of the two layers.

# Arguments
- `h_terms::AbstractVector{<:AbstractMatrix}`: Nearest-neighbor
  Hamiltonian terms, with `h_terms[i]` acting on sites `i` and `i+1`.
- `Δt::Number`: Real- or imaginary-time step.

# Returns
- `U_odd::MPO`: MPO containing the evolution gates on odd bonds.
- `U_even::MPO`: MPO containing the evolution gates on even bonds.

# Throws
- `ArgumentError`: If `h_terms` is empty.
- Errors propagated by `evolution_operator` or
  `split_two_site_operator` if any local Hamiltonian term has
  incompatible dimensions.

# Notes
All local terms are assumed to describe sites with the same physical
dimension `d`.
"""
function trotter_mpos(
    h_terms::AbstractVector{<:AbstractMatrix},
    Δt::Number,
)
    isempty(h_terms) &&
        throw(ArgumentError(
            "At least one nearest-neighbor Hamiltonian term is required."
        ))

    # N sites have N-1 nearest-neighbor terms.
    N = length(h_terms) + 1

    # Use the first gate to determine the local physical dimension
    # and resulting numerical element type.
    G₁ = evolution_operator(h_terms[1], Δt)
    L₁, R₁ = split_two_site_operator(G₁)

    d = size(L₁, 2)
    T = eltype(L₁.data)

    odd_tensors = Vector{Tensor{T,4}}(undef, N)
    even_tensors = Vector{Tensor{T,4}}(undef, N)

    # Initially every site is an identity in both layers.
    I_tensor = identity_mpo_tensor(d, T)

    for n in 1:N
        odd_tensors[n] = copy(I_tensor)
        even_tensors[n] = copy(I_tensor)
    end

    # Bond 1 is always odd. We already computed its decomposition.
    odd_tensors[1] = L₁
    odd_tensors[2] = R₁

    # Construct the remaining two-site gates.
    for i in 2:N-1
        G = evolution_operator(h_terms[i], Δt)
        L, R = split_two_site_operator(G)

        if isodd(i)
            odd_tensors[i] = L
            odd_tensors[i+1] = R
        else
            even_tensors[i] = L
            even_tensors[i+1] = R
        end
    end

    return MPO(odd_tensors), MPO(even_tensors)
end
